// blogs/src/views/Gallery/components/GalleryGrid.tsx
import type { GalleryItem } from '../../../content/gallery/data'
import { GalleryCard } from './GalleryCard'

type GalleryGridProps = {
  items: GalleryItem[]
  canLoadMore: boolean
  onLoadMore: () => void
}

export function GalleryGrid({
  items,
  canLoadMore,
  onLoadMore,
}: GalleryGridProps) {
  if (!items.length) {
    return (
      <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-10 text-center shadow-sm">
        <h2 className="text-2xl font-bold text-base_black">
          No gallery items match this filter.
        </h2>
        <p className="mt-3 text-sm leading-6 text-slate-500">
          Try another tag or add new entries
        </p>
      </div>
    )
  }

  return (
    <section className="flex flex-col gap-10">
      <div
        className="grid grid-cols-1 items-stretch gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
        aria-live="polite"
      >
        {items.map((item) => (
          <div key={item.id}>
            <GalleryCard item={item} />
          </div>
        ))}
      </div>

      {canLoadMore && (
        <div className="flex justify-center">
          <button
            type="button"
            className="bg-transparent px-6 py-2 text-sm font-medium text-primary"
            onClick={onLoadMore}
          >
            see more
          </button>
        </div>
      )}
    </section>
  )
}

// src/views/Gallery/components/GalleryGrid.vue
<template>
  <section v-if="items.length" class="flex flex-col gap-10">
    <div class="grid grid-cols-1 items-stretch gap-6 md:grid-cols-2 xl:grid-cols-3" aria-live="polite">
      <div
        v-for="item in items"
        :key="item.id"
        class="h-full"
      >
        <GalleryCard :item="item" />
      </div>
    </div>

    <div v-if="canLoadMore" class="flex justify-center">
      <button
        type="button"
        class="bg-transparent px-8 py-2 text-lg font-medium text-primary"
        @click="$emit('loadMore')"
      >
        see more
      </button>
    </div>
  </section>

  <div v-else class="rounded-[24px] border border-dashed border-slate-300 bg-white p-10 text-center shadow-sm">
    <h2 class="text-2xl font-bold text-base_black">No gallery items match this filter.</h2>
    <p class="mt-3 text-sm leading-6 text-slate-500">
      Try another tag or add new entries
    </p>
  </div>
</template>

<script setup>
import GalleryCard from './GalleryCard.vue'

defineProps({
  items: {
    type: Array,
    default: () => [],
  },
  canLoadMore: {
    type: Boolean,
    default: false,
  },
})

defineEmits(['loadMore'])
</script>
