// blogs/src/views/Gallery/components/GalleryCard.tsx
import { createPortal } from 'react-dom'
import { useEffect, useState } from 'react'
import galleryFallbackSample from '../../../../../src/views/Gallery/assets/gallery-fallback-sample.svg'
import type { GalleryItem } from '../../../content/gallery/data'
import {
  formatDate,
  getPlatformBadgeClass,
  getPlatformIcon,
  getPlatformKey,
  getZoomTitleId,
  wrapImageIndex,
} from '../utils'

type GalleryCardProps = {
  item: GalleryItem
}

export function GalleryCard({ item }: GalleryCardProps) {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [failedIndices, setFailedIndices] = useState<Set<number>>(new Set())
  const [isZoomOpen, setIsZoomOpen] = useState(false)
  const images = item.images.length ? item.images : item.image ? [item.image] : []
  const hasMultipleImages = images.length > 1
  const currentImage =
    !images[currentIndex] || failedIndices.has(currentIndex)
      ? galleryFallbackSample
      : images[currentIndex]
  const platformKey = getPlatformKey(item.type)
  const formattedDate = formatDate(item.date)
  const resolvedAlt = item.alt || item.id || 'Gallery item preview'
  const zoomTitleId = getZoomTitleId(item)
  const shouldShowPlatformBadge =
    platformKey === 'linkedin' || platformKey === 'instagram'

  useEffect(() => {
    setCurrentIndex(0)
    setFailedIndices(new Set())
    setIsZoomOpen(false)
  }, [item.id])

  useEffect(() => {
    if (typeof document === 'undefined') return
    if (!isZoomOpen) return

    const previousOverflow = document.body.style.overflow

    function handleZoomKeydown(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        setIsZoomOpen(false)
        return
      }

      if (!hasMultipleImages) return

      if (event.key === 'ArrowRight') {
        setCurrentIndex((index) => wrapImageIndex(index + 1, images.length))
      } else if (event.key === 'ArrowLeft') {
        setCurrentIndex((index) => wrapImageIndex(index - 1, images.length))
      }
    }

    document.addEventListener('keydown', handleZoomKeydown)
    document.body.style.overflow = 'hidden'

    return () => {
      document.removeEventListener('keydown', handleZoomKeydown)
      document.body.style.overflow = previousOverflow
    }
  }, [hasMultipleImages, images.length, isZoomOpen])

  function showImageAt(index: number) {
    if (!images.length) return

    setCurrentIndex(wrapImageIndex(index, images.length))
  }

  function handleImageError() {
    setFailedIndices((indices) => {
      if (indices.has(currentIndex)) return indices

      const nextIndices = new Set(indices)
      nextIndices.add(currentIndex)
      return nextIndices
    })
  }

  return (
    <>
      <article
        className={`group relative overflow-hidden rounded-b-[6px] rounded-t-none bg-white shadow-[0_12px_32px_-4px_rgba(14,20,27,0.08)] ring-1 ring-slate-900/5 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_18px_42px_-10px_rgba(14,20,27,0.14)] ${
          item.featured
            ? 'shadow-[0_18px_42px_-12px_rgba(24,128,230,0.2)] ring-primary/20'
            : ''
        }`}
      >
        <div className="relative h-[200px] overflow-hidden rounded-t-none bg-slate-100 sm:h-[220px]">
          {item.featured && (
            <span className="absolute top-3 right-3 z-10 inline-flex h-7 w-7 items-center justify-center rounded-[6px] bg-white/90 p-0 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] ring-1 ring-slate-900/10 backdrop-blur-sm">
              <span
                className="mdi mdi-star text-sm leading-none text-yellow-500"
                aria-hidden="true"
              />
            </span>
          )}
          <button
            type="button"
            className="absolute right-3 bottom-3 z-10 inline-flex h-8 w-8 items-center justify-center rounded-[6px] border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:outline-none"
            aria-label={`Zoom image: ${item.id || 'gallery item'}`}
            onClick={() => setIsZoomOpen(true)}
          >
            <span
              className="mdi mdi-magnify-plus-outline text-base leading-none"
              aria-hidden="true"
            />
          </button>
          <img
            src={currentImage}
            alt={resolvedAlt}
            className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]"
            loading="lazy"
            onError={handleImageError}
          />

          {hasMultipleImages && (
            <>
              <button
                type="button"
                className="absolute top-1/2 left-3 z-10 inline-flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:ring-2 focus:ring-primary focus:outline-none"
                aria-label="Previous image"
                onClick={() => showImageAt(currentIndex - 1)}
              >
                <span
                  className="mdi mdi-chevron-left text-[22px] leading-none"
                  aria-hidden="true"
                />
              </button>
              <button
                type="button"
                className="absolute top-1/2 right-3 z-10 inline-flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:ring-2 focus:ring-primary focus:outline-none"
                aria-label="Next image"
                onClick={() => showImageAt(currentIndex + 1)}
              >
                <span
                  className="mdi mdi-chevron-right text-[22px] leading-none"
                  aria-hidden="true"
                />
              </button>
              <div className="absolute bottom-3 left-1/2 z-10 flex -translate-x-1/2 items-center gap-1.5 rounded-full bg-slate-950/40 px-2 py-1 backdrop-blur-sm">
                {images.map((image, index) => (
                  <button
                    key={`${image}-${index}`}
                    type="button"
                    className={`h-1.5 rounded-full p-0 transition-all ${
                      index === currentIndex
                        ? 'w-4 bg-white'
                        : 'w-1.5 bg-white/60 hover:bg-white/80'
                    }`}
                    aria-label={`Show image ${index + 1} of ${images.length}`}
                    aria-current={index === currentIndex}
                    onClick={() => showImageAt(index)}
                  />
                ))}
              </div>
            </>
          )}
        </div>

        <div className="flex h-14 items-center border-t border-slate-100 px-3 py-2">
          <div className="flex w-full items-center justify-between gap-3">
            <div className="flex min-w-0 flex-col gap-0.5">
              {formattedDate && (
                <span className="inline-flex max-w-full items-center rounded-[6px] text-[10px] font-medium leading-tight text-slate-600/80">
                  <span
                    className="mdi mdi-calendar-blank-outline mr-1 shrink-0 text-xs leading-none text-slate-500"
                    aria-hidden="true"
                  />
                  <span className="truncate">{formattedDate}</span>
                </span>
              )}
              {item.location && (
                <span className="inline-flex max-w-full items-center rounded-[6px] text-[10px] leading-tight text-slate-600/80">
                  <span
                    className="mdi mdi-map-marker mr-1 shrink-0 text-xs leading-none text-slate-500"
                    aria-hidden="true"
                  />
                  <span className="truncate">{item.location}</span>
                </span>
              )}
            </div>

            {shouldShowPlatformBadge && item.externalUrl ? (
              <a
                href={item.externalUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-[6px] text-white shadow-[0_10px_24px_-16px_rgba(14,20,27,0.75)] transition-transform hover:scale-105 ${getPlatformBadgeClass(
                  platformKey,
                )}`}
                aria-label={`Open ${platformKey} post`}
              >
                <span
                  className={`mdi ${getPlatformIcon(platformKey)} text-lg leading-none`}
                  aria-hidden="true"
                />
              </a>
            ) : shouldShowPlatformBadge ? (
              <div
                className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-[6px] text-white shadow-[0_10px_24px_-16px_rgba(14,20,27,0.75)] ${getPlatformBadgeClass(
                  platformKey,
                )}`}
              >
                <span
                  className={`mdi ${getPlatformIcon(platformKey)} text-lg leading-none`}
                  aria-hidden="true"
                />
              </div>
            ) : null}
          </div>
        </div>
      </article>

      {isZoomOpen &&
        typeof document !== 'undefined' &&
        createPortal(
          <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 px-4 py-6"
            role="dialog"
            aria-modal="true"
            aria-labelledby={zoomTitleId}
            onClick={(event) => {
              if (event.target === event.currentTarget) setIsZoomOpen(false)
            }}
          >
            <div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-lg bg-slate-950 shadow-2xl">
              <header className="flex items-center justify-between gap-4 border-b border-white/10 px-4 py-3">
                <h2
                  id={zoomTitleId}
                  className="truncate text-base font-semibold text-white"
                >
                  {item.id || 'Gallery image'}
                </h2>

                <button
                  type="button"
                  className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-[6px] bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:ring-2 focus:ring-white/70 focus:outline-none"
                  aria-label="Close image zoom"
                  onClick={() => setIsZoomOpen(false)}
                >
                  <span
                    className="mdi mdi-close text-[22px] leading-none"
                    aria-hidden="true"
                  />
                </button>
              </header>

              <div className="relative flex min-h-0 flex-1 items-center justify-center bg-black">
                <img
                  src={currentImage}
                  alt={resolvedAlt}
                  className="max-h-[82vh] w-full object-contain"
                />

                {hasMultipleImages && (
                  <>
                    <button
                      type="button"
                      className="absolute top-1/2 left-4 inline-flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:ring-2 focus:ring-white/70 focus:outline-none"
                      aria-label="Previous image"
                      onClick={() => showImageAt(currentIndex - 1)}
                    >
                      <span
                        className="mdi mdi-chevron-left text-[26px] leading-none"
                        aria-hidden="true"
                      />
                    </button>
                    <button
                      type="button"
                      className="absolute top-1/2 right-4 inline-flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:ring-2 focus:ring-white/70 focus:outline-none"
                      aria-label="Next image"
                      onClick={() => showImageAt(currentIndex + 1)}
                    >
                      <span
                        className="mdi mdi-chevron-right text-[26px] leading-none"
                        aria-hidden="true"
                      />
                    </button>
                    <div className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-white">
                      {currentIndex + 1} / {images.length}
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>,
          document.body,
        )}
    </>
  )
}

// src/views/Gallery/components/GalleryCard.vue
<template>
  <article
    class="group relative flex h-full min-h-[30rem] flex-col overflow-hidden rounded-[12px] bg-white shadow-[0_12px_32px_-4px_rgba(14,20,27,0.08)] ring-1 ring-slate-900/5 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_18px_42px_-10px_rgba(14,20,27,0.14)]"
    :class="{ 'ring-primary/20 shadow-[0_18px_42px_-12px_rgba(24,128,230,0.2)]': item.featured }">
    <div class="flex items-start justify-between gap-4 px-4 pt-4">
      <div class="flex min-w-0 w-3/10 items-center gap-2">
        <div v-if="platformIcon"
          class="flex h-7 w-7 shrink-0 items-center justify-center rounded-[6px] text-white shadow-[0_10px_24px_-16px_rgba(14,20,27,0.75)]"
          :class="platformBadgeClass">
          <v-icon size="18">{{ platformIcon }}</v-icon>
        </div>

        <div class="min-w-0">
          <p class="truncate leading-tight text-xs font-semibold text-base_black block">
            <span class="block">{{ platformLabel }}</span>
            <span v-if="formattedDate" class="text-[11px] font-medium text-slate-600/80">
              {{ formattedDate }}
            </span>
          </p>
        </div>
      </div>
      <div class="flex w-7/10 shrink-0 self-stretch flex-col items-end justify-end gap-1">
        <span v-if="item.event" class="inline-flex w-full items-center justify-end rounded-[6px] text-[11px] text-right text-slate-600/80">
          <v-icon size="14" class="mr-1 shrink-0 text-grey-500">mdi-pillar</v-icon>
          <span class="truncate">{{ item.event }}</span>
        </span>
        <span v-if="item.location" class="inline-flex w-full items-center justify-end rounded-[6px] text-[11px] text-right text-slate-600/80">
          <v-icon size="14" class="mr-1 shrink-0 text-grey-500">mdi-map-marker</v-icon>
          <span class="truncate">{{ item.location }}</span>
        </span>
      </div>
    </div>

    <div class="relative mt-5 h-[240px] overflow-hidden bg-slate-100 sm:h-[260px]">
      <span
        v-if="item.featured"
        class="absolute right-3 top-3 z-10 inline-flex items-center justify-center rounded-[8px] bg-white/90 p-2 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] ring-1 ring-slate-900/10 backdrop-blur-sm">
        <v-icon size="16" class="text-yellow-500">mdi-star</v-icon>
      </span>
      <button
        type="button"
        class="absolute bottom-3 right-3 z-10 inline-flex h-10 w-10 items-center justify-center rounded-[8px] border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        :aria-label="`Zoom image: ${item.title || 'gallery item'}`"
        @click="openZoom"
      >
        <v-icon size="20">mdi-magnify-plus-outline</v-icon>
      </button>
      <Transition :name="slideTransitionName">
        <div :key="currentIndex" class="absolute inset-0">
          <img :src="currentImage" :alt="resolvedAlt"
            class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]" loading="lazy"
            @error="handleImageError">
        </div>
      </Transition>

      <template v-if="hasMultipleImages">
        <button
          type="button"
          class="absolute left-3 top-1/2 z-10 inline-flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary"
          aria-label="Previous image"
          @click="showPrevImage"
        >
          <v-icon size="22">mdi-chevron-left</v-icon>
        </button>
        <button
          type="button"
          class="absolute right-3 top-1/2 z-10 inline-flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-white/90 p-0 text-slate-700 shadow-[0_12px_24px_-14px_rgba(14,20,27,0.65)] backdrop-blur-sm transition-colors hover:border-white hover:bg-white hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary"
          aria-label="Next image"
          @click="showNextImage"
        >
          <v-icon size="22">mdi-chevron-right</v-icon>
        </button>
        <div class="absolute bottom-3 left-1/2 z-10 flex -translate-x-1/2 items-center gap-1.5 rounded-full bg-slate-950/40 px-2 py-1 backdrop-blur-sm">
          <button
            v-for="(image, index) in images"
            :key="index"
            type="button"
            class="relative h-1.5 overflow-hidden rounded-full p-0 transition-all"
            :class="index === currentIndex ? 'w-5 bg-white/40' : 'w-1.5 bg-white/60 hover:bg-white/80'"
            :aria-label="`Show image ${index + 1} of ${images.length}`"
            :aria-current="index === currentIndex"
            @click="showImageAt(index)"
          >
            <span
              v-if="index === currentIndex"
              :key="`dot-progress-${isZoomOpen}`"
              class="gallery-dot-progress absolute inset-0 rounded-full bg-white"
              :style="dotProgressStyle"
            />
          </button>
        </div>
      </template>
    </div>

    <div class="relative flex flex-1 flex-col gap-4 p-6">
      <h2 class="min-h-[3.125rem] font-serif text-[1.25rem] font-semibold leading-tight tracking-[-0.02em] text-base_black">
        {{ item.title }}
      </h2>

      <div class="min-h-[8.75rem] text-justify text-[0.90rem] leading-7 text-slate-500">
        <CaptionContent v-if="hasCaption" :text="item.caption" />
      </div>
      <div v-if="visibleTags.length || item.externalUrl" class="mt-auto flex w-full items-end gap-4">
        <div class="w-[90%]">
          <ul v-if="visibleTags.length" class="flex flex-wrap gap-2" aria-label="Gallery item tags">
            <li v-for="tag in visibleTags" :key="tag"
              class="rounded-[5px] bg-blue-100/50 px-1.5 py-1 text-[10px] font-semibold uppercase tracking-[0.10em] text-slate-600">
              {{ tag }}
            </li>
          </ul>
        </div>

        <div class="flex w-[10%] justify-end">
          <a v-if="item.externalUrl" :href="item.externalUrl" target="_blank" rel="noopener noreferrer"
            class="inline-flex h-10 w-10 shrink-0 items-center justify-center text-blue-500 no-underline hover:text-blue-800"
            aria-label="Open milestone">
            <v-icon size="18">mdi-open-in-new</v-icon>
          </a>
        </div>
      </div>
    </div>
  </article>

  <Teleport to="body">
    <Transition name="gallery-zoom-fade">
      <div
        v-if="isZoomOpen"
        class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 px-4 py-6"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="zoomTitleId"
        @click.self="closeZoom"
      >
        <div class="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-lg bg-slate-950 shadow-2xl">
          <header class="flex items-center justify-between gap-4 border-b border-white/10 px-4 py-3">
            <h2 :id="zoomTitleId" class="truncate text-base font-semibold text-white">
              {{ item.title || 'Gallery image' }}
            </h2>

            <button
              type="button"
              class="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-[6px] bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:outline-none focus:ring-2 focus:ring-white/70"
              aria-label="Close image zoom"
              @click="closeZoom"
            >
              <v-icon size="22">mdi-close</v-icon>
            </button>
          </header>

          <div class="relative flex min-h-0 flex-1 items-center justify-center bg-black">
            <img
              :src="currentImage"
              :alt="resolvedAlt"
              class="max-h-[82vh] w-full object-contain"
            >

            <template v-if="hasMultipleImages">
              <button
                type="button"
                class="absolute left-4 top-1/2 inline-flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:outline-none focus:ring-2 focus:ring-white/70"
                aria-label="Previous image"
                @click="showPrevImage"
              >
                <v-icon size="26">mdi-chevron-left</v-icon>
              </button>
              <button
                type="button"
                class="absolute right-4 top-1/2 inline-flex h-11 w-11 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 p-0 text-white transition-colors hover:bg-white/20 focus:outline-none focus:ring-2 focus:ring-white/70"
                aria-label="Next image"
                @click="showNextImage"
              >
                <v-icon size="26">mdi-chevron-right</v-icon>
              </button>
              <div class="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-white">
                {{ currentIndex + 1 }} / {{ images.length }}
              </div>
            </template>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import CaptionContent from '@/components/CaptionContent.vue'
import galleryFallbackSample from '../assets/gallery-fallback-sample.svg'

const props = defineProps({
  item: {
    type: Object,
    required: true,
  },
})

const formatter = new Intl.DateTimeFormat('en', {
  month: 'short',
  day: 'numeric',
  year: 'numeric',
})

const visibleTags = computed(() => (
  Array.isArray(props.item.tags)
    ? props.item.tags
      .filter(tag => typeof tag === 'string' && tag.trim())
    : []
))
const hasCaption = computed(() => (
  typeof props.item.caption === 'string' && props.item.caption.trim().length > 0
))
const AUTO_ROTATE_INTERVAL = 6000
const failedIndices = ref(new Set())
const currentIndex = ref(0)
const slideDirection = ref('next')
const isZoomOpen = ref(false)
let autoRotateTimer = null
const images = computed(() => {
  if (Array.isArray(props.item.images) && props.item.images.length) {
    return props.item.images
  }

  const remoteImage = typeof props.item.image === 'string'
    ? props.item.image.trim()
    : ''

  return remoteImage ? [remoteImage] : []
})
const hasMultipleImages = computed(() => images.value.length > 1)
const slideTransitionName = computed(() => `gallery-slide-${slideDirection.value}`)
const dotProgressStyle = computed(() => ({
  animationDuration: `${AUTO_ROTATE_INTERVAL}ms`,
  animationPlayState: isZoomOpen.value ? 'paused' : 'running',
}))
const currentImage = computed(() => {
  const source = images.value[currentIndex.value]

  return !source || failedIndices.value.has(currentIndex.value)
    ? galleryFallbackSample
    : source
})
const platformKey = computed(() => getPlatformKey(props.item.type))
const platformLabel = computed(() => getPlatformLabel(platformKey.value))

const platformIcon = computed(() => {
  if (platformKey.value === 'instagram') return 'mdi-instagram'
  if (platformKey.value === 'linkedin') return 'mdi-linkedin'
  if (platformKey.value === 'youtube') return 'mdi-youtube'
  if (platformKey.value === 'zoom') return 'mdi-video'
  if (platformKey.value === 'twitter') return 'mdi-twitter'
  return 'mdi-image-outline'
})

const platformBadgeClass = computed(() => {
  if (platformKey.value === 'instagram') return 'bg-gradient-to-br from-[#f9ce34] via-[#ee2a7b] to-[#6228d7]'
  if (platformKey.value === 'linkedin') return 'bg-[#0a66c2]'
  if (platformKey.value === 'youtube') return 'bg-[#ff0000]'
  if (platformKey.value === 'zoom') return 'bg-[#0b5cff]'
  if (platformKey.value === 'twitter') return 'bg-[#0f172a]'
  return 'bg-[#004f9a]'
})

const resolvedAlt = computed(() => (
  props.item.alt || props.item.title || 'Gallery item preview'
))
const zoomTitleId = computed(() => {
  const itemId = props.item.id || props.item.title || 'item'
  const normalizedId = String(itemId)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return `gallery-zoom-title-${normalizedId || 'item'}`
})

const formattedDate = computed(() => formatDate(props.item.date))

watch(() => props.item.id, () => {
  currentIndex.value = 0
  failedIndices.value = new Set()
  closeZoom()
  startAutoRotate()
})

watch(isZoomOpen, (isOpen) => {
  if (isOpen) stopAutoRotate()
  else startAutoRotate()

  if (typeof document === 'undefined') return

  if (isOpen) {
    document.addEventListener('keydown', handleZoomKeydown)
    document.body.style.overflow = 'hidden'
    return
  }

  document.removeEventListener('keydown', handleZoomKeydown)
  document.body.style.overflow = ''
})

onMounted(startAutoRotate)

onBeforeUnmount(() => {
  stopAutoRotate()

  if (typeof document === 'undefined') return

  document.removeEventListener('keydown', handleZoomKeydown)
  document.body.style.overflow = ''
})

function formatDate(value) {
  if (!value) return ''

  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    const [year, month, day] = value.split('-').map(Number)
    return formatter.format(new Date(year, month - 1, day))
  }

  const parsedDate = new Date(value)
  if (Number.isNaN(parsedDate.getTime())) return value

  return formatter.format(parsedDate)
}

function getPlatformKey(value) {
  const normalizedType = typeof value === 'string'
    ? value.trim().toLowerCase()
    : ''

  if (normalizedType === 'instagram') return 'instagram'
  if (normalizedType === 'linkedin') return 'linkedin'
  if (normalizedType === 'youtube') return 'youtube'
  if (normalizedType === 'zoom') return 'zoom'
  if (normalizedType === 'twitter') return 'twitter'
  return 'gallery'
}

function getPlatformLabel(value) {
  if (value === 'instagram') return 'Instagram'
  if (value === 'linkedin') return 'LinkedIn'
  if (value === 'youtube') return 'YouTube'
  if (value === 'zoom') return 'Zoom'
  if (value === 'twitter') return 'Twitter'
  return 'Uploaded'
}

function handleImageError() {
  if (failedIndices.value.has(currentIndex.value)) return

  const nextFailedIndices = new Set(failedIndices.value)
  nextFailedIndices.add(currentIndex.value)
  failedIndices.value = nextFailedIndices
}

function stopAutoRotate() {
  if (autoRotateTimer) {
    clearInterval(autoRotateTimer)
    autoRotateTimer = null
  }
}

function startAutoRotate() {
  stopAutoRotate()

  if (!hasMultipleImages.value || isZoomOpen.value) return

  autoRotateTimer = setInterval(() => {
    slideDirection.value = 'next'
    currentIndex.value = (currentIndex.value + 1) % images.value.length
  }, AUTO_ROTATE_INTERVAL)
}

function showImageAt(index, direction = '') {
  const total = images.value.length
  if (total === 0) return

  const nextIndex = ((index % total) + total) % total
  slideDirection.value = direction || (nextIndex >= currentIndex.value ? 'next' : 'prev')
  currentIndex.value = nextIndex
  startAutoRotate()
}

function showPrevImage() {
  showImageAt(currentIndex.value - 1, 'prev')
}

function showNextImage() {
  showImageAt(currentIndex.value + 1, 'next')
}

function openZoom() {
  isZoomOpen.value = true
}

function closeZoom() {
  isZoomOpen.value = false
}

function handleZoomKeydown(event) {
  if (event.key === 'Escape') {
    closeZoom()
    return
  }

  if (!hasMultipleImages.value) return

  if (event.key === 'ArrowRight') showNextImage()
  else if (event.key === 'ArrowLeft') showPrevImage()
}
</script>

<style scoped>
.gallery-dot-progress {
  transform-origin: left;
  animation: gallery-dot-fill linear both;
}

@keyframes gallery-dot-fill {
  from {
    transform: scaleX(0);
  }

  to {
    transform: scaleX(1);
  }
}

.gallery-slide-next-enter-active,
.gallery-slide-next-leave-active,
.gallery-slide-prev-enter-active,
.gallery-slide-prev-leave-active {
  transition: transform 450ms ease;
}

.gallery-slide-next-enter-from {
  transform: translateX(100%);
}

.gallery-slide-next-leave-to {
  transform: translateX(-100%);
}

.gallery-slide-prev-enter-from {
  transform: translateX(-100%);
}

.gallery-slide-prev-leave-to {
  transform: translateX(100%);
}

.gallery-zoom-fade-enter-active,
.gallery-zoom-fade-leave-active {
  transition: opacity 160ms ease;
}

.gallery-zoom-fade-enter-from,
.gallery-zoom-fade-leave-to {
  opacity: 0;
}
</style>
