// blogs/src/views/PrivacyPolicy/index.tsx
import { PRIVACY_SECTION } from '../../content/sections'
import { PAGE_DESCRIPTIONS } from '../../content/descriptions'
import { SITE_PROFILE } from '../../content/site'
import { usePageTitle } from '../../lib/usePageTitle'

const POLICY_SECTIONS = [
  {
    title: 'Information you provide',
    body: (
      <p>
        This blog does not provide user accounts, comments, newsletter signup,
        or contact forms. Information is only received when you choose to
        contact the author by email or through a linked external service.
      </p>
    ),
  },
  {
    title: 'Hosting and visit data',
    body: (
      <p>
        The blog is hosted on{' '}
        <a
          href="https://www.cloudflare.com/policies/privacy/"
          target="_blank"
          rel="noreferrer"
        >
          Cloudflare
        </a>
        . Hosting infrastructure may process standard request data such as IP
        address, browser type, requested page, referring page, and request time
        to deliver and protect the site. The footer also loads Flag Counter, a
        third-party visit counter that may receive request and device
        information when its image is displayed.
      </p>
    ),
  },
  {
    title: 'Local storage and travel maps',
    body: (
      <p>
        Travel-map features cache geocoding and route results in your browser&apos;s
        local storage to reduce repeated network requests. This cache stays on
        your device and can be removed through your browser&apos;s site-data
        controls. Map views may request data from geocoding, map-data, and
        routing providers, which receive the technical information needed to
        answer those requests.
      </p>
    ),
  },
  {
    title: 'Remote content and external services',
    body: (
      <p>
        Pages may load{' '}
        <a
          href="https://developers.google.com/fonts/faq/privacy"
          target="_blank"
          rel="noreferrer"
        >
          Google Fonts
        </a>
        , book covers, photographs, maps, or other media from third-party
        hosts. Links and share actions can take you to social networks, video
        platforms, reference sites, and other services. Those providers operate
        under their own privacy policies and may collect data independently of
        this blog.
      </p>
    ),
  },
  {
    title: 'Cookies and advertising',
    body: (
      <p>
        The blog does not intentionally set advertising cookies or create
        behavioural advertising profiles. Third-party resources opened or
        loaded from this blog may use their own storage or tracking technologies
        according to their policies and your browser settings.
      </p>
    ),
  },
] as const

export function PrivacyPolicyPage() {
  usePageTitle(PRIVACY_SECTION.title)

  return (
    <article className="mx-auto w-full max-w-6xl pb-8">
      <header className="mb-8 border-b border-border pb-8 text-center">
        <h1 className="text-4xl leading-tight font-black text-ink">
          {PRIVACY_SECTION.title}
        </h1>
        <p className="mx-auto mt-4 max-w-3xl text-base leading-7 text-muted">
          {PAGE_DESCRIPTIONS.privacy}
        </p>
        <p className="mt-3 text-sm text-faint">
          {PRIVACY_SECTION.lastUpdatedLabel}: {PRIVACY_SECTION.lastUpdated}
        </p>
      </header>

      <div className="grid grid-cols-1 border-t border-border lg:grid-cols-2">
        {POLICY_SECTIONS.map((section, index) => (
          <section
            key={section.title}
            className={`border-b border-border py-6 lg:py-8 ${
              index % 2 === 0 ? 'lg:border-r lg:pr-8' : 'lg:pl-8'
            }`}
          >
            <h2 className="mb-2 text-lg leading-7 font-bold text-ink">
              {section.title}
            </h2>
            <div className="text-justify text-base leading-7 text-muted">
              {section.body}
            </div>
          </section>
        ))}

        <section className="border-b border-border py-6 lg:py-8 lg:pl-8">
          <h2 className="mb-2 text-lg leading-7 font-bold text-ink">Contact</h2>
          <p className="text-justify text-base leading-7 text-muted">
            For privacy questions, corrections, or removal requests, email{' '}
            <a className="font-semibold" href={`mailto:${SITE_PROFILE.email}`}>
              {SITE_PROFILE.email}
            </a>
            .
          </p>
        </section>
      </div>
    </article>
  )
}

// src/views/PrivacyPolicy.vue
<template>
  <div class="relative flex size-full min-h-screen flex-col bg-slate-50 overflow-x-hidden">
    <div class="layout-container flex h-full grow flex-col">
      <div class="px-8 md:px-16 lg:px-20 flex flex-1 justify-center py-10">
        <div class="layout-content-container flex flex-col w-full max-w-[960px] flex-1">
          <div class="mb-10 text-center">
            <p class="text-sm font-semibold uppercase tracking-[0.3em] text-[#4e7397]">
              Privacy Policy
            </p>
            <h1 class="mt-3 text-4xl font-black tracking-[-0.033em] text-[#0e141b]">
              Your information stays treated with care.
            </h1>
            <p class="mt-4 text-sm text-slate-600">
              Last updated: <time datetime="2026-10-07">October 7, 2026</time>
            </p>
          </div>

          <ul class="list-disc space-y-4 pl-6 text-slate-600 marker:text-[#1980e6]">
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Information shown on this site:</span>
              The content on this website is curated portfolio information such as profile details, education, projects, publications, and public contact links.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Information you provide:</span>
              This public portfolio does not offer visitor accounts, login, or contact forms. Contact links open your email application or a third-party platform. If you send an email, your email address and message are used to respond to your enquiry.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Hosting and technical data:</span>
              Hosting and content delivery providers may process standard request information, such as your IP address, browser details, requested pages, and request times, to deliver the site, maintain security, and diagnose errors.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Visitor statistics (Flag Counter):</span>
              The footer automatically loads a Flag Counter image to display visitor counts by country or region; no click is needed. This sends your IP address, browser and operating-system information, and any referrer information supplied by your browser to Boardhost.com, Inc., which says its servers are in the United States. According to its
              <a href="https://www.flagcounter.com/privacy.html" class="font-semibold text-[#0f62fe] hover:text-[#0842a0]" target="_blank" rel="noopener noreferrer">privacy policy</a>,
              Flag Counter uses your IP address to estimate your country or region and creates a counter-specific hash to limit repeat counting. The hash is kept for up to seven days; the provider says it does not log visitors' IP addresses.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Certification badge summary:</span>
              The Certifications page may request a public summary of my Credly badges from a hosted endpoint. This request retrieves badge counts and issuer information; it does not ask for your Credly account or login details. The endpoint's hosting provider may process standard technical request data.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">External services and links:</span>
              This site links to third-party platforms such as Credly, GitHub, LinkedIn, Google Drive, Google Scholar, and ResearchGate. Opening those links, or loading content hosted by another provider, may share standard request information with that provider. Those services have their own privacy practices and terms.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Cookies and analytics:</span>
              The portfolio application does not currently set its own cookies. Flag Counter states that its embedded counter image does not use cookies, although its separate statistics website may use cookies and advertising when you follow the counter link. Other external services have their own cookie practices.
            </li>
            <li class="content-justify">
              <span class="font-semibold text-[#0e141b]">Contact:</span>
              For privacy-related questions, corrections, or removal requests, please reach out at
              <a :href="emailLink" class="font-semibold text-[#0f62fe] hover:text-[#0842a0]">{{ email }}</a>.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import config from '@/content/profile_info'

// The policy's contact-of-record is the personal gmail address (it was
// contacts.email before that key was renamed to contacts.gmail).
const email = config.contacts.gmail
const emailLink = `mailto:${email}`
</script>
