// blogs/src/components/Header/index.tsx
import { useState } from 'react'
import { NavLink } from 'react-router-dom'
import { isFeatureEnabled } from '../../config/featureFlags'
import {
  FACTS_NAV_LABEL,
  FACTS_URL,
  MAIN_SITE_URL,
  NAV_ITEMS,
  PORTFOLIO_NAV_LABEL,
} from '../../content/navigation'
import { SITE_PROFILE } from '../../content/site'

const MUTED_LINK_CLASS =
  'relative text-sm leading-normal font-medium text-[#6b7280] transition-colors duration-200 hover:text-primary'

function navLinkClass({ isActive }: { isActive: boolean }): string {
  return isActive
    ? 'relative text-sm leading-normal font-bold text-primary transition-colors duration-200'
    : 'relative text-sm leading-normal font-medium text-ink transition-colors duration-200 hover:text-primary'
}

export function Header() {
  const [drawerOpen, setDrawerOpen] = useState(false)
  const enabledNavItems = NAV_ITEMS.filter((item) => isFeatureEnabled(item.flag))

  return (
    <>
      <header className="sticky top-0 z-50 flex items-center justify-between border-b border-header-border bg-surface px-10 py-4 whitespace-nowrap">
        <div
          className="inline-flex items-center gap-4 text-lg leading-tight font-bold tracking-[-0.015em] whitespace-nowrap text-ink"
          aria-label={SITE_PROFILE.name}
        >
          <span className="inline-flex size-4 flex-none overflow-hidden rounded-full bg-surface-soft">
            <img className="size-full object-cover" src={SITE_PROFILE.profileIconPath} alt="" />
          </span>
          <span>{SITE_PROFILE.name}</span>
        </div>

        <div className="flex flex-1 items-center justify-end gap-8">
          <nav
            className="hidden items-center gap-9 md:flex"
            aria-label="Primary navigation"
          >
            {enabledNavItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                className={navLinkClass}
                end={item.to === '/'}
              >
                {item.label}
              </NavLink>
            ))}
            {isFeatureEnabled('showFactsLink') && (
              <a href={FACTS_URL} className={MUTED_LINK_CLASS}>
                {FACTS_NAV_LABEL}
              </a>
            )}
            {isFeatureEnabled('showPortfolioLink') && (
              <a href={MAIN_SITE_URL} className={MUTED_LINK_CLASS}>
                {PORTFOLIO_NAV_LABEL}
              </a>
            )}
          </nav>

          <button
            className="flex size-10 cursor-pointer items-center justify-center border-0 bg-transparent p-0 text-black transition-colors duration-200 hover:text-primary md:hidden"
            type="button"
            aria-label="Open menu"
            aria-expanded={drawerOpen}
            onClick={() => setDrawerOpen((open) => !open)}
          >
            <span className="mdi mdi-menu text-2xl leading-none" aria-hidden="true" />
          </button>
        </div>
      </header>

      {drawerOpen && (
        <div
          className="fixed inset-0 z-50 bg-black/50"
          onClick={() => setDrawerOpen(false)}
        >
          <div
            className="absolute top-0 right-0 h-full w-64 bg-white shadow-[0_20px_45px_rgba(15,23,42,0.18)]"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="mb-6 flex items-center justify-between px-4 pt-4">
              <h3 className="text-lg leading-normal font-bold text-ink">Menu</h3>
              <button
                className="size-6 cursor-pointer border-0 bg-transparent p-0 text-ink hover:text-primary"
                type="button"
                aria-label="Close menu"
                onClick={() => setDrawerOpen(false)}
              >
                <span className="mdi mdi-close text-2xl leading-none" aria-hidden="true" />
              </button>
            </div>
            <nav
              className="flex flex-col gap-4 px-4 pb-4"
              aria-label="Mobile navigation"
            >
              {enabledNavItems.map((item) => (
                <NavLink
                  key={item.to}
                  to={item.to}
                  className={navLinkClass}
                  end={item.to === '/'}
                  onClick={() => setDrawerOpen(false)}
                >
                  {item.label}
                </NavLink>
              ))}
              {isFeatureEnabled('showFactsLink') && (
                <a
                  href={FACTS_URL}
                  className={MUTED_LINK_CLASS}
                  onClick={() => setDrawerOpen(false)}
                >
                  {FACTS_NAV_LABEL}
                </a>
              )}
              {isFeatureEnabled('showPortfolioLink') && (
                <a
                  href={MAIN_SITE_URL}
                  className={MUTED_LINK_CLASS}
                  onClick={() => setDrawerOpen(false)}
                >
                  {PORTFOLIO_NAV_LABEL}
                </a>
              )}
            </nav>
          </div>
        </div>
      )}
    </>
  )
}

// src/components/Header.vue
<template>
  <header
    class="sticky top-0 z-50 bg-white flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#e7edf3] px-10 py-2">
    <!-- Logo/Brand -->
    <div class="flex items-center gap-4 text-base_black">
      <div class="size-4">
        <img src="/profile-icon.png" alt="Profile Icon" class="w-full h-full object-cover rounded-full" />
      </div>
      <router-link to="/" class="text-base_black text-lg font-bold leading-tight tracking-[-0.015em] no-underline">
        {{ profile.name }}
      </router-link>
    </div>

    <!-- Navigation Links -->
    <div class="flex flex-1 justify-end gap-8">
      <div class="hidden md:flex items-center gap-9">
        <router-link to="/" class="nav-link" active-class="active-link">
          Home
        </router-link>
        <router-link
          v-if="showProjectsPublicationsNavLink"
          to="/projects-publications"
          class="nav-link"
          active-class="active-link"
        >
          Projects & Publications
        </router-link>
        <router-link v-if="showTeachingsNavLink" to="/teachings" class="nav-link" active-class="active-link">
          Teachings
        </router-link>
        <router-link
          v-if="showProfessionalActivityNavLink"
          to="/professional-activity"
          class="nav-link"
          active-class="active-link"
        >
          Professional Activity
        </router-link>
        <router-link :to="{ name: 'Contact' }" class="nav-link" active-class="active-link">
          Contact
        </router-link>
        <router-link v-if="showGalleryNavLink" to="/gallery" class="nav-link" active-class="active-link">
          Gallery
        </router-link>
      </div>

      <!-- Mobile Menu Button -->
      <button class="md:hidden flex items-center justify-center w-10 h-10 transition-colors duration-200"
        @click="drawer = !drawer">

        <v-icon color="black" size="24">
          mdi-menu
        </v-icon>

      </button>
    </div>
  </header>

  <!-- Mobile Navigation Drawer -->
  <div v-if="drawer" class="fixed inset-0 z-50 md:hidden" @click.self="drawer = false">
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-black bg-opacity-50"></div>

    <!-- Drawer Content -->
    <div class="absolute right-0 top-0 h-full w-64 bg-white shadow-lg">
      <div class="flex flex-col p-4">
        <div class="flex justify-between items-center mb-6">
          <h3 class="text-lg font-bold text-base_black">Menu</h3>
          <button @click="drawer = false" class="text-base_black hover:text-primary transition-colors duration-200">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>

        <nav class="flex flex-col space-y-4">
          <router-link to="/" @click="drawer = false" class="nav-link" active-class="active-link">
            Home
          </router-link>
          <router-link
            v-if="showGalleryNavLink"
            to="/gallery"
            @click="drawer = false"
            class="nav-link"
            active-class="active-link"
          >
            Gallery
          </router-link>
          <router-link
            v-if="showProjectsPublicationsNavLink"
            to="/projects-publications"
            @click="drawer = false"
            class="nav-link"
            active-class="active-link"
          >
            Projects & Publications
          </router-link>
          <router-link v-if="showTeachingsNavLink" to="/teachings" @click="drawer = false" class="nav-link" active-class="active-link">
            Teachings
          </router-link>
          <router-link
            v-if="showProfessionalActivityNavLink"
            to="/professional-activity"
            @click="drawer = false"
            class="nav-link"
            active-class="active-link"
          >
            Professional Activity
          </router-link>
          <router-link :to="{ name: 'Contact' }" @click="drawer = false" class="nav-link" active-class="active-link">
            Contact
          </router-link>
        </nav>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import config from "@/profile_info.yml"
import { isFeatureEnabled } from '@/config/featureFlags'

const router = useRouter()
const drawer = ref(false)
const { profile } = config

const showGalleryNavLink = computed(() => (
  isFeatureEnabled('showGallery') && router.hasRoute('Gallery')
))

const showTeachingsNavLink = computed(() => (
  isFeatureEnabled('showTeachings', { mode: 'any' }) && router.hasRoute('Teachings')
))

const showProjectsPublicationsNavLink = computed(() => (
  isFeatureEnabled('showProjectsPublications', { mode: 'any' })
  && router.hasRoute('ProjectsPublications')
))

const showProfessionalActivityNavLink = computed(() => (
  isFeatureEnabled('showProfessionalActivity', { mode: 'any' })
  && (router.hasRoute('ProfessionalActivity') || router.hasRoute('ProfessionalAcitivity'))
))

</script>

<style scoped>
.no-underline {
  text-decoration: none;
}

.nav-link {
  @apply text-base_black text-sm font-medium transition-colors duration-200 no-underline;
}

.nav-link:hover {
  @apply text-primary;
}

.active-link {
  @apply font-bold text-primary;
}
</style>
